import 'package:intl/intl.dart';
import 'package:moneywise/features/loans/domain/loan_model.dart';
import 'package:moneywise/features/transactions/domain/transaction_model.dart';
import 'package:moneywise/shared/enums/transaction_type.dart';
import 'package:moneywise/shared/models/category_total.dart';
import 'package:moneywise/shared/models/loan_summary.dart';
import 'package:moneywise/shared/models/transaction_summary.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfReportGenerator {
  static Future<void> generate({
    required TransactionSummary summary,
    required List<CategoryTotal> categoryTotals,
    required List<TransactionEntity> topTransactions,
    required LoanSummary loanSummary,
    required List<LoanEntity> unsettledLoans,
    required String monthYear,
    required String currency,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateStr = DateFormat('dd MMM yyyy, hh:mm a').format(now);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 20),
          child: pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount} • Generated by Moneywise',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
          ),
        ),
        build: (context) => [
          // Header
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Moneywise Report',
                      style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: const PdfColor.fromInt(0xFF3D2C8D))),
                  pw.Text('Financial statement for $monthYear', style: const pw.TextStyle(fontSize: 14)),
                ],
              ),
              pw.Text('Generated: $dateStr', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
            ],
          ),
          pw.SizedBox(height: 10),
          pw.Divider(thickness: 1, color: PdfColors.grey300),
          pw.SizedBox(height: 20),

          // Summary Section
          pw.Text('Summary', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 12),
          pw.TableHelper.fromTextArray(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
            headerDecoration: const pw.BoxDecoration(color: PdfColors.grey700),
            cellAlignment: pw.Alignment.centerLeft,
            data: [
              ['Label', 'Amount'],
              ['Total Income', '$currency${summary.totalIncome.toStringAsFixed(2)}'],
              ['Total Expense', '$currency${summary.totalExpense.toStringAsFixed(2)}'],
              ['Net Balance', '$currency${summary.netBalance.toStringAsFixed(2)}'],
              ['Savings Rate', '${summary.savingsRate.toStringAsFixed(1)}%'],
            ],
          ),
          pw.SizedBox(height: 30),

          // Category Breakdown
          pw.Text('Category Breakdown', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 12),
          pw.TableHelper.fromTextArray(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            data: [
              ['Category', 'Spent', '% of Total'],
              ...categoryTotals.map((t) => [
                    t.categoryName,
                    '$currency${t.total.toStringAsFixed(2)}',
                    '${summary.totalExpense > 0 ? (t.total / summary.totalExpense * 100).toStringAsFixed(1) : "0"}%',
                  ]),
              [
                'Total',
                '$currency${summary.totalExpense.toStringAsFixed(2)}',
                '100%',
              ],
            ],
          ),
        ],
      ),
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 20),
          child: pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount} • Generated by Moneywise',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
          ),
        ),
        build: (context) => [
          // Top Transactions
          pw.Text('Top 10 Transactions', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 12),
          pw.TableHelper.fromTextArray(
            border: pw.TableBorder.all(color: PdfColors.grey300),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            data: [
              ['Date', 'Title', 'Type', 'Amount'],
              ...topTransactions.take(10).map((t) => [
                    DateFormat('dd/MM/yy').format(t.date),
                    t.title,
                    t.type.name.toUpperCase(),
                    '${t.type == TransactionType.income ? "+" : "-"}$currency${t.amount.toStringAsFixed(0)}',
                  ]),
            ],
          ),
          pw.SizedBox(height: 30),

          // Loan Summary
          pw.Text('Loan Summary', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 12),
          pw.Row(
            children: [
              pw.Expanded(
                child: pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(border: pw.TableBorder.all(color: PdfColors.grey300)),
                  child: pw.Column(
                    children: [
                      pw.Text('Total to Receive', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                      pw.Text('$currency${loanSummary.totalGave.toStringAsFixed(0)}',
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.green)),
                    ],
                  ),
                ),
              ),
              pw.Expanded(
                child: pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(border: pw.TableBorder.all(color: PdfColors.grey300)),
                  child: pw.Column(
                    children: [
                      pw.Text('Total to Pay', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
                      pw.Text('$currency${loanSummary.totalTook.toStringAsFixed(0)}',
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.red)),
                    ],
                  ),
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 16),
          if (unsettledLoans.isNotEmpty) ...[
            pw.Text('Unsettled Loans', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.TableHelper.fromTextArray(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              data: [
                ['Person', 'Amount', 'Due Date', 'Status'],
                ...unsettledLoans.map((l) => [
                      l.personName,
                      '$currency${l.amount.toStringAsFixed(0)}',
                      l.dueDate != null ? DateFormat('dd/MM/yy').format(l.dueDate!) : 'None',
                      l.isPaid ? 'Settled' : 'Unpaid',
                    ]),
              ],
            ),
          ],
        ],
      ),
    );

    await Printing.sharePdf(bytes: await pdf.save(), filename: 'moneywise_$monthYear.pdf');
  }
}
